### PR TITLE
Mm copy functions

### PR DESCRIPTION
**Pull request by mitchellmanware**
1. Migrate NARR, GEOS-CF, HMS, GMTED, and SEDAC population functions and tests from `beethoven`
2. Merge with current `process.R` and `calculate_covariates.R` files
3. Add spatial subset test data sets
4. Update README.md
5. `download_noaa_hms_smoke_data` > `download_hms_data` (reflected in `man/` and all tests)
6. Utilize base R `strsplit()` in the `extract_urls()` download support function.
  - Replaced `stringr` dependency with `stringi` for `stringi::stri_pad()` in `process_narr()`

### CODE REVIEW

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
@mitchellmanware I'm not sure what to do. I would suggest first updating your branch with main as I am seeing this warning from GitHub (i.e. your branch is both ahead and behind main). Interestingly the build checks and test-coverage appeared to take 3-4x longer than when they ran for me.

**Comment by mitchellmanware** [comment]
Pulled in the updates so we will see if that makes a difference. 

It is weird how the different Ubuntu versions fail the build check seemingly randomly. In [this commit](https://github.com/Spatiotemporal-Exposures-and-Toxicology/amadeus/pull/15/commits/2a33e6c5e64bc261c3d850a8a4f4d3a7fe22f0de) oldrel-1 was the only to fail, but [later](https://github.com/Spatiotemporal-Exposures-and-Toxicology/amadeus/pull/15/commits/c072d79c1342e7baafeacdd987c2fe9c3c3ec093) it is the only one to pass.

I assume it stems from whatever is causing the testthat upload to fail, but changing the `Sys.sleep()` values in both the `test_download_functions()` function and in the `test-downoad_functions.R` tests causes unpredictable pass/failure.

The unit tests run very quick locally, so also unsure about the running time in the GitHub runners.
@Spatiotemporal-Exposures-and-Toxicology

**Comment by mitchellmanware** [comment]
Somehow the `httr2` package resulted in **three hour** run times for the R CMD checks. Not sure how this is possible but I will revert to previous version with `httr`.

**Comment by mitchellmanware** [comment]
I am now getting test failures for `process_geos_collection`, which is a simple string splitting and selection function. I am going to close PR and create new branch from most recent merge from `main`.

**Pull request closed without merging**
